### ISSUE TITLE
get_stats_valuation not working | yahoo finance error?!

### ISSUE THREAD

**Issue by JonathanWillnow** [atreadw1492/yahoo_fin#118]
Example:

print(si.get_stats_valuation("MMM"))

Following Error:
Traceback (most recent call last):
  File "C:\Users\Jonathan\Documents\Stock_project\stock-site\screen.py", line 17, in <module>
    print(si.get_stats_valuation("MMM"))
  File "C:\Users\Jonathan\Documents\Stock_project\env\lib\site-packages\yahoo_fin\stock_info.py", line 362, in get_stats_valuation
    table = tables[0].reset_index(drop = True)
IndexError: list index out of range

When I look at the error and trace it back to line 362 in get_stats_valuation, it seems that the error is on the end of yahoo finance as the following link

    stats_site = "https://finance.yahoo.com/quote/" + ticker + \
                 "/key-statistics?p=" + ticker
    
seems not to be working any more.

Am I right in the assumption that this error is related to YF and not to the code itself?
Did this happen before?

Cheers and thanks for all the work!

**Comment by JonathanWillnow** [comment]
Was a temporary error on the end of yahoo finance. Now it works again. 

Issue Closed
