### ISSUE TITLE
options.get_expiration_dates(TICKER) Not Returning Proper Values

### ISSUE THREAD

**Issue by zjorge96** [atreadw1492/yahoo_fin#53]
I have been running into an error where the "get_expiration_dates()" will return only a couple dates are an entirely empty list. For example when working it will return this:
MOS
['June 25, 2021', 'July 2, 2021', 'July 9, 2021', 'July 16, 2021', 'July 23, 2021', 'July 30, 2021', 'September 17, 2021', 'December 17, 2021', 'January 21, 2022', 'January 20, 2023']

But the next time it runs will return this:
MOS
['January 21, 2022', 'January 20, 2023']
or
MOS
[]
Resulting in an error like below because there is no dates in the list.
Traceback (most recent call last):
  File "c:\Users\User\Documents\options.py", line 300, in <module>
    bo.topFive(chosen_sector)
  File "c:\Users\User\Documents\options.py", line 116, in topFive
    call = self.closestCallStrike(sector[i], cur_stock_price, closing_dates[0])
IndexError: list index out of range

**Comment by zjorge96** [comment]
Made a quick tester program to check:

from yahoo_fin import options
i = 0
while i < 100:
    closing_dates = options.get_expiration_dates("MOS")
    print(closing_dates)
    i += 1

After 39 iterations of it working correctly, the loop slows down and starts only grabbing the last two dates ['January 21, 2022', 'January 20, 2023']

**Comment by zjorge96** [comment]
Possibly came up with a temporary solution. Adding a simple second delay "time.sleep(1)" is allowing it to function properly. Assuming it was just getting overloaded with requests.

**Comment by mathias5986** [comment]
Hello,

Has this issue been solved ? I am having the same problem.
Sometimes it shows 3 expiration dates and sometimes it shows all:

![image](https://user-images.githubusercontent.com/74938818/139733986-94a6c613-b4e4-4b4b-a97a-86a1fc2f9b53.png)


![image](https://user-images.githubusercontent.com/74938818/139734028-f338c941-a254-4a59-a97a-9cccd4c28210.png)


This is so strange..

thanks,

Mathias
