### ISSUE TITLE
Error after updating to Py 3.7 and reinstalling yahoo_fin

### ISSUE THREAD

**Issue by seranki** [atreadw1492/yahoo_fin#60]
After updating to Py 3.7.10 and reinstalling yahoo_fin 0.8.9, I am getting the following error:

`>>> si.get_live_price(ticker) 
 
Traceback (most recent call last):  
  File "<stdin>", line 1, in <module>  
  File "/Volumes/Backup/Users/......./anaconda3/lib/python3.7/site-packages/yahoo_fin/stock_info.py", line 575, in get_live_price  
    df = get_data(ticker, end_date = pd.Timestamp.today() + pd.DateOffset(10))  
  File "/Volumes/Backup/Users/......./anaconda3/lib/python3.7/site-packages/yahoo_fin/stock_info.py", line 88, in get_data  
    raise AssertionError(resp.json())  
  File "/Volumes/Backup/Users/......./anaconda3/lib/python3.7/site-packages/requests/models.py", line 900, in json  
    return complexjson.loads(self.text, **kwargs)  
  File "/Volumes/Backup/Users/......./anaconda3/lib/python3.7/json/__init__.py", line 348, in loads  
    return _default_decoder.decode(s)  
  File "/Volumes/Backup/Users/......./anaconda3/lib/python3.7/json/decoder.py", line 337, in decode  
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())  
  File "/Volumes/Backup/Users/......./anaconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode  
    raise JSONDecodeError("Expecting value", s, err.value) from None  
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)  
`

All the modules seem to be satisfying the dependency requirements of yahoo_fin

**Comment by jaydevshelat** [comment]
+1 something broke in last 12-18 hours. I made no version changes.  I have been successfully using Py 3.8.3  and  yahoo_fin 0.8.6  for a while now.

**Comment by seranki** [comment]
@atreadw1492 Please see the author's response to a recent YF issue with a different module:
[Error raised by query2.finance.yahoo.com #32](https://github.com/mcdallas/wallstreet/issues/32)
It may or may not fix the issue reported above with yahoo_fin

**Comment by atreadw1492** [comment]
@seranki @jaydevshelat Please update to the latest version - 0.8.9.1.  This should resolve the issues you're seeing.
