### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by bobdabuilder1** [atreadw1492/yahoo_fin#66]
On version 0.8.9.1 I keep randomly getting a list index out of range error. It will happen on a ticker and then the next time it won't.

Traceback (most recent call last):
  File "yahoofintest.py", line 153, in <module>
    Earnings_History = si.get_earnings_history(i)
  File "/home/****/.local/lib/python3.8/site-packages/yahoo_fin/stock_info.py", line 836, in get_earnings_history
    result = _parse_earnings_json(url)
  File "/home/****/.local/lib/python3.8/site-packages/yahoo_fin/stock_info.py", line 809, in _parse_earnings_json
    page_data = [row for row in content.split(
IndexError: list index out of range

**Comment by josiahswanson** [comment]
I am experiencing this problem, too. In a for loop, it will actually start happening with one ticker and then keep erroring on the remaining tickers in the loop.

**Comment by daanvonkHOB** [comment]
Experiencing similar error. 

Sometimes it does succesfully load get_stats_valuation for a single ticker, but within the for loop all tickers get this error.

**Comment by mpainenz** [comment]
I ran into this issue with the Earnings Calendar, and now when I try to view the Earnings calendar from my Browser, I'm redirected to the homepage for Yahoo.

I wanted to post here, in case others experience this, as I was blocked because I made too many API calls presumably. If you have this issue, check with your browser that you can get to the corresponding page of the service you are accessing via python.

I managed to get around this issue by using a Proxy. The Requests pakage that yahoo_fin uses, allows you to specify a proxy via windows command line (which is handy).

**Comment by arup1221** [comment]
i am getting 
data = tables[0].append(tables[1])
IndexError: list index out of range

can anyone have any kind of solution or I am got blocked?

**Comment by chinmayagrawal775** [comment]
I am also getting this error.

actually tables[1] does not exists..

Looks like the API reponse has been changes, by yahoo-fin package has not been updated..
